# Generated by Django 3.2.18 on 2025-03-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAPIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('appname', models.CharField(help_text='业务应用名称', max_length=200, verbose_name='业务应用名称')),
                ('appdesc', models.TextField(help_text='接口描述', null=True, verbose_name='接口描述')),
                ('appurl', models.CharField(help_text='接口地址', max_length=200, null=True, verbose_name='接口地址')),
                ('appkey', models.CharField(help_text='接口KEY', max_length=200, null=True, verbose_name='接口KEY')),
                ('tip_type', models.IntegerField(choices=[(1, '数据分析'), (2, '其他')], default=1, verbose_name='提示词类型')),
                ('tip_ctt', models.CharField(help_text='提示词内容', max_length=200, null=True, verbose_name='提示词内容')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '应用接口模型',
                'db_table': 'kg_appapimodel',
            },
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模型名称', max_length=200, verbose_name='接口名称')),
                ('no', models.IntegerField(help_text='模型编号', null=True, verbose_name='模型编号')),
                ('function', models.TextField(help_text='接口功能', null=True, verbose_name='接口功能')),
                ('desc', models.TextField(help_text='接口描述', null=True, verbose_name='接口描述')),
                ('url', models.CharField(help_text='接口地址', max_length=200, null=True, verbose_name='接口地址')),
                ('version', models.CharField(help_text='版本号', max_length=200, null=True, verbose_name='版本号')),
                ('req_type', models.IntegerField(help_text='请求方式', max_length=1, null=True, verbose_name='请求方式')),
                ('activate', models.IntegerField(help_text='激活状态', max_length=1, null=True, verbose_name='激活状态')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库数据接口',
                'db_table': 'kg_datamodel',
            },
        ),
        migrations.CreateModel(
            name='DataModelParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='参数名称', max_length=20, verbose_name='参数名称')),
                ('type', models.CharField(help_text='参数类型', max_length=20, null=True, verbose_name='参数类型')),
                ('default', models.CharField(help_text='默认值', max_length=20, null=True, verbose_name='默认值')),
                ('desc', models.CharField(help_text='参数说明', max_length=20, null=True, verbose_name='参数说明')),
                ('necessary', models.IntegerField(help_text='必须参数', max_length=1, null=True, verbose_name='必须参数')),
                ('activate', models.IntegerField(help_text='激活状态', max_length=1, null=True, verbose_name='激活状态')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('kg_model_id', models.ForeignKey(blank=True, help_text='关联模型', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataapp.datamodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name_plural': '数据接入接口参数',
                'db_table': 'kg_datamodel_param',
            },
        ),
    ]
