# Generated by Django 3.2.18 on 2024-12-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0002_initial'),
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='business_tag',
            field=models.ForeignKey(blank=True, help_text='关联的业务标签', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kgapp.kgtag', verbose_name='业务标签'),
        ),
    ]
