# Generated by Django 3.2.18 on 2025-03-31 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataapp', '0002_datamodel_business_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='kg_user_data_id',
            field=models.ForeignKey(blank=True, help_text='创建作者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建作者'),
        ),
        migrations.AddField(
            model_name='appapimodel',
            name='toolapis',
            field=models.ManyToManyField(blank=True, help_text='工具集接口', to='dataapp.DataModel', verbose_name='工具集接口'),
        ),
    ]
