# Generated by Django 3.2.18 on 2025-01-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_datamodel_business_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAPIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('appname', models.CharField(help_text='业务应用名称', max_length=200, verbose_name='业务应用名称')),
                ('appdesc', models.TextField(help_text='接口描述', null=True, verbose_name='接口描述')),
                ('appurl', models.CharField(help_text='接口地址', max_length=200, null=True, verbose_name='接口地址')),
                ('appkey', models.CharField(help_text='接口KEY', max_length=200, null=True, verbose_name='接口KEY')),
                ('tip_type', models.IntegerField(choices=[(1, '数据分析'), (2, '其他')], default=1, verbose_name='提示词类型')),
                ('tip_ctt', models.CharField(help_text='提示词内容', max_length=200, null=True, verbose_name='提示词内容')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('toolapis', models.ManyToManyField(blank=True, help_text='工具集接口', to='dataapp.DataModel', verbose_name='工具集接口')),
            ],
            options={
                'verbose_name_plural': '应用接口模型',
                'db_table': 'kg_appapimodel',
            },
        ),
    ]
