version: '3.8'
services:
  kgproj:
    container_name: kgproj
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DB_HOST=mysql
      - DB_NAME=kgproj
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=20221qaz@WSX
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=12345678
      - REDIS_URL=redis://redis:6379
      - ES_URL=http://elasticsearch:9200
      - ES_PORT=9200
      - ES_HOST=elasticsearch
      - ES_USER=elastic
      - ES_PWD=elastic
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true