version: '3.8'

# 定义网络（优化为自定义子网，避免IP冲突）
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24  # 修改为新的子网

# 定义数据卷（持久化数据与宿主机解耦）
volumes:
  mysql_data:
  redis_data:
  es_data:
  neo4j_data:

# 定义服务
services:
  base_nginx:
    image: nginx:latest
    container_name: base_nginx
    ports:
      - "80:80"
      - "7000:7000"
      - "5000:5000"
      - "9999:9999"
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/front_ui:/usr/share/nginx/front_ui
      - ./dist/backend_ui:/usr/share/nginx/backend_ui
      - ./dist/kgfrontui:/usr/share/nginx/kgfrontui
      - ./mainapp/media:/usr/share/nginx/media
networks:
  mynetwork:
    external: true
