# Generated by Django 3.2.18 on 2025-03-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='业务名称', max_length=200, verbose_name='业务名称')),
                ('code', models.CharField(help_text='业务代号', max_length=10, verbose_name='业务代号')),
                ('desc', models.CharField(blank=True, help_text='业务描述', max_length=512, null=True, verbose_name='业务描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '业务',
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisplayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='问题', max_length=512, verbose_name='问题')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '展示问题',
                'db_table': 'display_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='业务名称', max_length=200, verbose_name='业务名称')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库业务表',
                'db_table': 'kg_business',
            },
        ),
        migrations.CreateModel(
            name='KgDataIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('template_num', models.IntegerField(default=0, help_text='模板数量', null=True, verbose_name='模板数量')),
                ('qa_num', models.IntegerField(default=0, help_text='问答数量', null=True, verbose_name='问答数量')),
                ('rel_num', models.IntegerField(default=0, help_text='问答数量', null=True, verbose_name='关系数量')),
                ('ent_num', models.IntegerField(default=0, help_text='实体数量', null=True, verbose_name='实体数量')),
                ('doc_num', models.IntegerField(default=0, help_text='文档数量', null=True, verbose_name='文档数量')),
                ('span_type', models.IntegerField(default=0, help_text='统计类型', null=True, verbose_name='统计类型 -> 0(分钟)|1(小时)|2(日级别)|3(月级别)|4|5')),
                ('span_value', models.CharField(default='', help_text='下标间歇值', max_length=20, null=True, verbose_name='下标间歇值')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识统计指数',
                'db_table': 'kg_data_index',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgDDRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='规则名称', max_length=200, verbose_name='规则名称')),
                ('desc', models.CharField(help_text='规则描述', max_length=512, verbose_name='规则描述')),
                ('type', models.IntegerField(default=0, help_text='0|1  类型. 0:决策树', max_length=1, null=True, verbose_name='类型')),
                ('order', models.IntegerField(help_text='优先级 （暂未实际使用）', max_length=1, null=True, verbose_name='优先级')),
                ('status', models.IntegerField(default=0, help_text='1：生效，0：未生效', max_length=1, verbose_name='1：生效，0：未生效')),
                ('action_id', models.IntegerField(help_text='目标id', null=True, verbose_name='目标id')),
                ('content', models.TextField(default=0, help_text='规则详情', max_length=1024, verbose_name='规则详情')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '调度规则',
                'db_table': 'kg_dd_rule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgDDRuleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='规则名称', max_length=200, verbose_name='规则名称')),
                ('zhName', models.CharField(help_text='规则名称', max_length=200, verbose_name='规则名称')),
                ('type', models.IntegerField(help_text='1|2', max_length=1, null=True, verbose_name='类型 1(条件)|2(动作)')),
                ('valueType', models.CharField(help_text='值类型', max_length=200, verbose_name='值类型')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '调度规则属性',
                'db_table': 'kg_dd_attr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='文本标题', max_length=200, verbose_name='文本标题')),
                ('size', models.IntegerField(help_text='文本大小', null=True, verbose_name='文本大小')),
                ('type', models.CharField(help_text='文本类型', max_length=20, null=True, verbose_name='文本类型')),
                ('desc', models.TextField(help_text='文件描述', null=True, verbose_name='文件描述')),
                ('path', models.FileField(upload_to='docs', verbose_name='关联文件')),
                ('star', models.IntegerField(default=0, help_text='星指数', null=True, verbose_name='星指数')),
                ('parseflag', models.IntegerField(default=0, help_text='解析状态', null=True, verbose_name='解析状态')),
                ('structflag', models.IntegerField(default=0, help_text='结构化标识', null=True, verbose_name='结构化标识')),
                ('isdelete', models.IntegerField(help_text='是否删除', null=True, verbose_name='是否删除')),
                ('prodflag', models.IntegerField(default=0, help_text='生产状态', null=True, verbose_name='生产状态')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库文档',
                'db_table': 'kg_doc',
            },
        ),
        migrations.CreateModel(
            name='KgDocCttTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='分片ID', max_length=200, verbose_name='分片ID')),
                ('weight', models.FloatField(help_text='权重', null=True, verbose_name='权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '知识库文档标签',
                'db_table': 'kg_doc_ctt_tag',
            },
        ),
        migrations.CreateModel(
            name='KgDocFragmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('no', models.IntegerField(help_text='分片ID', max_length=200, verbose_name='分片ID')),
                ('content', models.TextField(help_text='分片内容', null=True, verbose_name='分片内容')),
                ('ctt_size', models.IntegerField(help_text='分片大小', max_length=200, null=True, verbose_name='分片大小')),
                ('activate_flag', models.IntegerField(default=1, help_text='启用状态', null=True, verbose_name='启用状态')),
                ('recall_cnt', models.IntegerField(default=0, help_text='召回次数', max_length=200, null=True, verbose_name='召回次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '知识库文档分片',
                'db_table': 'kg_doc_fragmentation',
            },
        ),
        migrations.CreateModel(
            name='KgEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='实体名称', max_length=200, verbose_name='实体名称')),
                ('type', models.CharField(help_text='实体类型', max_length=200, verbose_name='实体类型')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱实体',
                'db_table': 'kg_entity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgEntityAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('attname', models.CharField(help_text='实体属性名称', max_length=200, verbose_name='实体属性名称')),
                ('atttvalue', models.CharField(help_text='实体属性值', max_length=512, verbose_name='实体属性值')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱实体属性',
                'db_table': 'kg_entity_att',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgEntityAttrScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('attname', models.CharField(help_text='实体属性名称', max_length=200, verbose_name='实体属性名称')),
                ('atttype', models.CharField(help_text='实体属性类型', max_length=200, verbose_name='实体属性类型')),
                ('attmulti', models.IntegerField(help_text='0|1', max_length=1, null=True, verbose_name='单多值')),
                ('attdesc', models.CharField(help_text='实体属性描述', max_length=512, null=True, verbose_name='实体属性描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱实体属性约束',
                'db_table': 'kg_entity_att_scheme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgEntityScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='实体类型名称', max_length=200, verbose_name='实体类型名称')),
                ('color', models.CharField(default='#9AA1AC', help_text='实体展示颜色', max_length=200, verbose_name='实体展示颜色')),
                ('size', models.IntegerField(default=60, help_text='实体展示大小', verbose_name='实体展示大小')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱实体约束',
                'db_table': 'kg_entity_scheme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgProductTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='任务名称', max_length=200, verbose_name='任务名称')),
                ('desc', models.CharField(help_text='任务描述', max_length=512, verbose_name='任务描述')),
                ('task_type', models.IntegerField(help_text='生产类型', max_length=1, null=True, verbose_name='生产类型 0(知识导入)|1(自动生成)|2(全文生产)')),
                ('task_status', models.IntegerField(help_text='0|1|2|3', max_length=1, null=True, verbose_name='任务执行状态')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识生产',
                'db_table': 'kg_product_task',
            },
        ),
        migrations.CreateModel(
            name='KgQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='问题', max_length=200, verbose_name='问题')),
                ('answer', models.CharField(help_text='答案', max_length=512, verbose_name='答案')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '问答对结果',
                'db_table': 'kg_qa',
            },
        ),
        migrations.CreateModel(
            name='KgRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='关系名称', max_length=200, verbose_name='关系名称')),
                ('from_nodeid', models.IntegerField(null=True, verbose_name='from node')),
                ('to_nodeid', models.IntegerField(null=True, verbose_name='to node')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱关系',
                'db_table': 'kg_relation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgRelationScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='关系名称', max_length=200, verbose_name='关系名称')),
                ('desc', models.CharField(help_text='关系描述', max_length=512, verbose_name='关系描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识图谱关系约束',
                'db_table': 'kg_relation_scheme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgTableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='目录名称', max_length=200, verbose_name='目录名称')),
                ('no', models.IntegerField(help_text='目录编号', null=True, verbose_name='目录编号')),
                ('parent_id', models.IntegerField(default=0, help_text='父节点编号', null=True, verbose_name='父节点编号')),
                ('order_no', models.IntegerField(help_text='顺序编号', null=True, verbose_name='顺序编号')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库文档目录',
                'db_table': 'kg_table_content',
            },
        ),
        migrations.CreateModel(
            name='KgTabTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='一级标签名称', max_length=200, verbose_name='一级标签名称')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '一级目录标签',
                'db_table': 'kg_tab_tag',
            },
        ),
        migrations.CreateModel(
            name='KgTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='标签名称', max_length=200, unique=True, verbose_name='标签名称')),
                ('desc', models.CharField(help_text='标签描述', max_length=512, verbose_name='标签描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库标签',
                'db_table': 'kg_tag',
            },
        ),
        migrations.CreateModel(
            name='KgTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('celery_id', models.CharField(help_text='异步任务ID', max_length=512, verbose_name='异步任务ID')),
                ('task_step', models.IntegerField(help_text='0|1', max_length=1, null=True, verbose_name='任务步骤')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '细分异步执行任务记录',
                'db_table': 'kg_task',
            },
        ),
        migrations.CreateModel(
            name='KgTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模板名称', max_length=200, verbose_name='模板名称')),
                ('desc', models.TextField(help_text='模板描述', null=True, verbose_name='模板描述')),
                ('version', models.CharField(help_text='版本', max_length=30, verbose_name='版本')),
                ('activate', models.IntegerField(help_text='激活状态', max_length=1, null=True, verbose_name='激活状态')),
                ('path', models.FileField(upload_to='temps', verbose_name='关联文件')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库业务模板',
                'db_table': 'kg_templates',
            },
        ),
        migrations.CreateModel(
            name='KgTempTableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='目录名称', max_length=200, verbose_name='目录名称')),
                ('no', models.IntegerField(help_text='目录编号', null=True, unique=True, verbose_name='目录编号')),
                ('parent_id', models.IntegerField(default=0, help_text='父节点编号', null=True, verbose_name='父节点编号')),
                ('order_no', models.IntegerField(help_text='顺序编号', null=True, verbose_name='顺序编号')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识库模板目录',
                'db_table': 'kg_temp_table_content',
            },
        ),
        migrations.CreateModel(
            name='KgText2SQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('query', models.CharField(help_text='查询语句', max_length=512, verbose_name='查询语句')),
                ('sql_ctt', models.CharField(help_text='SQL内容', max_length=512, verbose_name='SQL内容')),
                ('activate', models.IntegerField(choices=[(0, '错误'), (1, '正确')], default=1, verbose_name='转换状态')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': 'Text2SQL',
                'db_table': 'kg_txttosql',
            },
        ),
        migrations.CreateModel(
            name='KgUpLoadTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='模版描述', max_length=200, verbose_name='模版描述')),
                ('path', models.FileField(upload_to='kguploadtemplates', verbose_name='关联文件')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '知识上传摸板',
                'db_table': 'kg_load_template',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hashid', models.CharField(help_text='知识库ID', max_length=200, verbose_name='知识库ID')),
                ('name', models.TextField(help_text='知识库名称', null=True, verbose_name='知识库名称')),
                ('desc', models.TextField(help_text='知识库描述', null=True, verbose_name='知识库描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '知识库',
                'db_table': 'kg_knowledge',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='分类名称', max_length=200, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, help_text='分类描述', max_length=512, null=True, verbose_name='分类描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '问题分类',
                'db_table': 'question_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KgTmpQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='问题', max_length=200, verbose_name='问题')),
                ('answer', models.CharField(help_text='答案', max_length=512, verbose_name='答案')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('doc_id', models.ForeignKey(blank=True, help_text='关联文件', null=True, on_delete=django.db.models.deletion.CASCADE, to='kgapp.kgdoc', verbose_name='关联文件')),
                ('task_id', models.ForeignKey(blank=True, help_text='任务来源', null=True, on_delete=django.db.models.deletion.CASCADE, to='kgapp.kgproducttask', verbose_name='任务来源')),
            ],
            options={
                'verbose_name_plural': '问答对临时解析结果',
                'db_table': 'kg_tmp_qa',
            },
        ),
    ]
