# Generated by Django 3.2.18 on 2025-02-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='业务名称', max_length=200, verbose_name='业务名称')),
                ('desc', models.CharField(blank=True, help_text='业务描述', max_length=512, null=True, verbose_name='业务描述')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '业务',
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='分类名称', max_length=200, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, help_text='分类描述', max_length=512, null=True, verbose_name='分类描述')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('bus', models.ForeignKey(help_text='业务', null=True, on_delete=django.db.models.deletion.CASCADE, to='kgapp.business', verbose_name='业务')),
            ],
            options={
                'verbose_name_plural': '问题分类',
                'db_table': 'question_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisplayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='问题', max_length=512, verbose_name='问题')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(help_text='分类', null=True, on_delete=django.db.models.deletion.CASCADE, to='kgapp.questioncategory', verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '展示问题',
                'db_table': 'display_question',
                'managed': True,
            },
        ),
    ]
