# Generated by Django 3.2.18 on 2025-02-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0003_business_displayquestion_questioncategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='bus',
        ),
        migrations.AddField(
            model_name='displayquestion',
            name='business',
            field=models.ForeignKey(blank=True, help_text='业务', null=True, on_delete=django.db.models.deletion.CASCADE, to='kgapp.business', verbose_name='业务'),
        ),
    ]
