# Generated by Django 3.2.18 on 2025-03-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0002_auto_20250311_1034'),
        ('kgapp', '0003_auto_20250311_1049'),
    ]

    operations = [
    ]
