# Generated by Django 3.2.18 on 2025-02-06 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kgapp', '0004_auto_20250205_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, help_text='业务代号', max_length=10, verbose_name='业务代号'),
            preserve_default=False,
        ),
    ]
