# Generated by Django 3.2.18 on 2025-03-18 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 32, 57, 824563), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 32, 57, 824563), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 32, 57, 824563), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 32, 57, 824563), null=True, verbose_name='更新时间'),
        ),
    ]
