# Generated by Django 3.2.18 on 2025-03-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userapp', '0003_auto_20250318_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 834423), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 834423), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 834423), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 834423), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='new_user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='new_user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
