# Generated by Django 3.2.18 on 2024-12-26 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20241226_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 15, 3, 18, 102610), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 15, 3, 18, 102610), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 15, 3, 18, 102610), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 15, 3, 18, 102610), null=True, verbose_name='更新时间'),
        ),
    ]
