# Generated by Django 3.2.18 on 2025-01-15 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_merge_0009_auto_20241226_1503_0009_auto_20241231_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 41, 38, 148108), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 41, 38, 148108), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 41, 38, 148639), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 41, 38, 148639), null=True, verbose_name='更新时间'),
        ),
    ]
