# Generated by Django 3.2.18 on 2024-10-29 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgmodel',
            name='kg_user_id',
            field=models.ForeignKey(blank=True, help_text='创建作者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建作者'),
        ),
    ]
