# Generated by Django 3.2.18 on 2024-12-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_kgmodel_kg_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kgmodel',
            table='kg_model',
        ),
    ]
