DATABASES:
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: 'kgproj'
    USER: 'root'
    PASSWORD: '20221qaz@WSX'
    HOST: '127.0.0.1'
    PORT: '3306'
    ENGINE: 'django.db.backends.sqlite3'
    NAME: 'db.sqlite3'

SECRET_KEY: 'your_secret_key'

DEBUG: true
SECRET_KEY: 'django-insecure-r&6c!_n9591qjq1&h6w4&!b%yk7l_%$dw2n8_k&++q#@0nh&vc'
LOG_LEVEL: INFO

ALLOWED_HOSTS:
  - '*'

NEO4J_URI: 'bolt://localhost:7687'
NEO4J_USERNAME: 'neo4j'
NEO4J_PASSWORD: '12345678'
REDIS_URL: 'redis://localhost:6379/0'

USE_LOCAL_MODEL: true
MODEL_PATH: /data/bge-large-zh
DATA_UPLOAD_MAX_MEMORY_SIZE: 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE: 10485760
TTF_PATH: /usr/share/fonts/dejavu/DejaVuSans.ttf
WKING_PATH: /usr/bin/wkhtmltoimage
YUAN_TEMPLET_PATH: data/yuan_templet/yuan_v1.json