# Generated by Django 3.2.18 on 2024-12-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShuiKu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='站名', max_length=200, verbose_name='站名')),
                ('stcd', models.CharField(help_text='站号', max_length=200, verbose_name='站号')),
            ],
            options={
                'verbose_name_plural': '水库数据表',
                'db_table': 'shuiku',
            },
        ),
        migrations.CreateModel(
            name='ShuiWen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='站名', max_length=200, verbose_name='站名')),
                ('stcd', models.CharField(help_text='站号', max_length=200, verbose_name='站号')),
            ],
            options={
                'verbose_name_plural': '水文数据表',
                'db_table': 'shuiwen',
            },
        ),
        migrations.CreateModel(
            name='ShuiKuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inflow', models.FloatField(null=True, verbose_name='入库流量')),
                ('outflow', models.FloatField(null=True, verbose_name='出库流量')),
                ('sw', models.FloatField(null=True, verbose_name='水位')),
                ('xx_sw', models.FloatField(null=True, verbose_name='汛限水位')),
                ('xl', models.FloatField(null=True, verbose_name='蓄水量（亿m³）')),
                ('diff_xl', models.FloatField(null=True, verbose_name='超蓄水量（亿m³）')),
                ('sy_kr', models.FloatField(null=True, verbose_name='剩余防洪库容（亿m³）')),
                ('sediment', models.FloatField(null=True, verbose_name='淤积量（亿m³）')),
                ('sediment_rate', models.FloatField(null=True, verbose_name='泥沙含量（%）')),
                ('date', models.DateTimeField(null=True, verbose_name='日期')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sk_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiku', verbose_name='水库')),
            ],
            options={
                'verbose_name_plural': '水库数据表',
                'db_table': 'shuiku_data',
            },
        ),
        migrations.CreateModel(
            name='HoleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='孔洞名称', max_length=200, verbose_name='孔洞名称')),
                ('stcd', models.CharField(help_text='孔洞编号', max_length=200, verbose_name='孔洞编号')),
                ('waterflow', models.FloatField(blank=True, null=True, verbose_name='排水流量')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('status', models.BooleanField(null=True, verbose_name='运行状态')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sk_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiku', verbose_name='水库')),
            ],
            options={
                'verbose_name_plural': '孔洞数据表',
                'db_table': 'hole',
            },
        ),
        migrations.CreateModel(
            name='HeDaoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('flow_h8', models.FloatField(null=True, verbose_name='流量')),
                ('date', models.DateTimeField(null=True, verbose_name='日期')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sw_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiwen', verbose_name='水文站')),
            ],
            options={
                'verbose_name_plural': '河道数据表',
                'db_table': 'hedao_data',
            },
        ),
        migrations.CreateModel(
            name='GenerateSetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='机组名称', max_length=200, verbose_name='机组名称')),
                ('stcd', models.CharField(help_text='机组编号', max_length=200, verbose_name='机组编号')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='发电容量')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='发电功率')),
                ('waterflow', models.FloatField(blank=True, null=True, verbose_name='排水流量')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('status', models.BooleanField(null=True, verbose_name='运行状态')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sk_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiku', verbose_name='水库')),
            ],
            options={
                'verbose_name_plural': '机组数据表',
                'db_table': 'generate_set',
            },
        ),
        migrations.CreateModel(
            name='FutureShuiKuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='模型名称', max_length=200, verbose_name='模型名称')),
                ('model_id', models.CharField(help_text='模型ID', max_length=200, verbose_name='模型ID')),
                ('name', models.CharField(help_text='站名', max_length=200, verbose_name='站名')),
                ('stcd', models.CharField(help_text='站号', max_length=200, verbose_name='站号')),
                ('inflow', models.FloatField(null=True, verbose_name='入库流量')),
                ('outflow', models.FloatField(null=True, verbose_name='出库流量')),
                ('sw', models.FloatField(null=True, verbose_name='水位')),
                ('xx_sw', models.FloatField(null=True, verbose_name='汛限水位')),
                ('xl', models.FloatField(null=True, verbose_name='蓄水量（亿m³）')),
                ('diff_xl', models.FloatField(null=True, verbose_name='超蓄水量（亿m³）')),
                ('sy_kr', models.FloatField(null=True, verbose_name='剩余防洪库容（亿m³）')),
                ('sediment', models.FloatField(null=True, verbose_name='淤积量（亿m³）')),
                ('sediment_rate', models.FloatField(null=True, verbose_name='泥沙含量（%）')),
                ('date', models.DateTimeField(null=True, verbose_name='日期')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sk_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiku', verbose_name='水库')),
            ],
            options={
                'verbose_name_plural': '未来水库数据表',
                'db_table': 'future_shuiku',
            },
        ),
        migrations.CreateModel(
            name='FutureHeDaoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='模型名称', max_length=200, verbose_name='模型名称')),
                ('model_id', models.CharField(help_text='模型ID', max_length=200, verbose_name='模型ID')),
                ('name', models.CharField(help_text='站名', max_length=200, verbose_name='站名')),
                ('stcd', models.CharField(help_text='站号', max_length=200, verbose_name='站号')),
                ('flow_h8', models.FloatField(null=True, verbose_name='流量')),
                ('date', models.DateTimeField(null=True, verbose_name='日期')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('sw_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydapp.shuiwen', verbose_name='水文')),
            ],
            options={
                'verbose_name_plural': '未来预报河道数据表',
                'db_table': 'future_hedao',
            },
        ),
    ]
