# Generated by Django 3.2.18 on 2024-12-15 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hydapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuikudata',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='站名', max_length=200, verbose_name='站名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuikudata',
            name='stcd',
            field=models.CharField(default=1, help_text='站号', max_length=200, verbose_name='站号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='futurehedaodata',
            name='flow_h8',
            field=models.FloatField(null=True, verbose_name='8时流量'),
        ),
    ]
