# Generated by Django 3.2.15 on 2024-10-22 09:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='预案名称')),
                ('ctype', models.IntegerField(blank=True, choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '其他')], default=0, verbose_name='预案模板类型')),
                ('word_data', models.JSONField(blank=True, verbose_name='word数据')),
                ('html_data', models.JSONField(blank=True, verbose_name='html数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户临时预案',
                'verbose_name_plural': '用户临时预案',
            },
        ),
        migrations.CreateModel(
            name='WordParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('ctype', models.IntegerField(choices=[(0, '标题'), (1, '文本'), (2, '图片'), (3, '表格'), (4, '其他')], default=1, verbose_name='文本类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '段落节点内容',
                'verbose_name_plural': '段落节点内容',
            },
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template', models.TextField(blank=True)),
                ('result', ckeditor.fields.RichTextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='用于排序的字段')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wordParagraphs', models.ManyToManyField(blank=True, to='yaapp.WordParagraph', verbose_name='内容节点')),
            ],
            options={
                'verbose_name': '节点列表',
                'verbose_name_plural': '节点列表',
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ctype', models.IntegerField(choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '其他')], default=0, verbose_name='预案模板类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodes', models.ManyToManyField(blank=True, to='yaapp.TemplateNode', verbose_name='内容节点')),
            ],
            options={
                'verbose_name': '预案模板',
                'verbose_name_plural': '预案模板',
            },
        ),
        migrations.CreateModel(
            name='PlanByUserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='plans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaapp.planbyuser')),
            ],
            options={
                'verbose_name': '预案文档',
                'verbose_name_plural': '预案文档',
            },
        ),
        migrations.AddField(
            model_name='planbyuser',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='yaapp.TemplateNode', verbose_name='内容节点'),
        ),
    ]
