# Generated by Django 3.2.18 on 2025-03-31 09:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='预案名称')),
                ('yadate', models.CharField(blank=True, default='2024-01-01', help_text='预案日期', max_length=10, null=True)),
                ('ctype', models.IntegerField(blank=True, choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '黄河汛情及水库调度方案单'), (4, '其他')], default=0, verbose_name='预案模板类型')),
                ('word_data', models.JSONField(blank=True, null=True, verbose_name='word数据')),
                ('html_data', models.JSONField(blank=True, null=True, verbose_name='html数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户临时预案',
                'verbose_name_plural': '用户临时预案',
            },
        ),
        migrations.CreateModel(
            name='PtBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='业务名称', max_length=200, verbose_name='业务名称')),
                ('code', models.CharField(help_text='业务代号', max_length=10, verbose_name='业务代号')),
                ('desc', models.CharField(blank=True, help_text='业务描述', max_length=512, null=True, verbose_name='业务描述')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '预案业务',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WordParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('ctype', models.IntegerField(choices=[(0, '标题'), (1, '文本'), (2, '图片'), (3, '表格'), (4, '其他')], default=1, verbose_name='文本类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '段落节点内容',
                'verbose_name_plural': '段落节点内容',
            },
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template', models.TextField(blank=True)),
                ('result', ckeditor.fields.RichTextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='用于排序的字段')),
                ('upload_file_flag', models.BooleanField(default=False, verbose_name='是否上传文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wordParagraphs', models.ManyToManyField(blank=True, to='yaapp.WordParagraph', verbose_name='内容节点')),
            ],
            options={
                'verbose_name': '节点列表',
                'verbose_name_plural': '节点列表',
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ctype', models.IntegerField(choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '黄河汛情及水库调度方案单'), (4, '其他')], default=0, verbose_name='预案模板类型')),
                ('published', models.BooleanField(default=False, verbose_name='发布状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='预案业务', null=True, on_delete=django.db.models.deletion.CASCADE, to='yaapp.ptbusiness', verbose_name='预案业务')),
                ('nodes', models.ManyToManyField(blank=True, to='yaapp.TemplateNode', verbose_name='内容节点')),
            ],
            options={
                'verbose_name': '预案模板',
                'verbose_name_plural': '预案模板',
            },
        ),
        migrations.CreateModel(
            name='PlanByUserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='outplans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaapp.planbyuser')),
            ],
            options={
                'verbose_name': '预案文档',
                'verbose_name_plural': '预案文档',
            },
        ),
        migrations.AddField(
            model_name='planbyuser',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='yaapp.TemplateNode', verbose_name='内容节点'),
        ),
        migrations.AddField(
            model_name='planbyuser',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
