# Generated by Django 3.2.18 on 2025-03-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbyuser',
            name='ctype',
            field=models.IntegerField(blank=True, choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '黄河汛情及水库调度方案单'), (4, '其他')], default=0, verbose_name='预案模板类型'),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='ctype',
            field=models.IntegerField(choices=[(0, '黄河中下游'), (1, '小浪底秋汛'), (2, '小浪底调水调沙'), (3, '黄河汛情及水库调度方案单'), (4, '其他')], default=0, verbose_name='预案模板类型'),
        ),
    ]
