# Generated by Django 3.2.15 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantemplate',
            name='published',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
    ]
