# Generated by Django 3.2.15 on 2024-10-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0002_plantemplate_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
