# Generated by Django 3.2.15 on 2024-10-23 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0003_plantemplate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantemplate',
            options={'verbose_name': '预案模板节点', 'verbose_name_plural': '预案模板节点'},
        ),
        migrations.RenameField(
            model_name='planbyuserdocument',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='planbyuserdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planbyuserdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
