# Generated by Django 3.2.15 on 2024-11-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0005_auto_20241024_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatenode',
            name='upload_file_flag',
            field=models.BooleanField(default=False, verbose_name='是否上传文件'),
        ),
    ]
