# Generated by Django 3.2.15 on 2024-11-13 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0006_templatenode_upload_file_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbyuser',
            name='yadate',
            field=models.CharField(default=1, help_text='预案日期', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='yadate',
            field=models.CharField(default=django.utils.timezone.now, help_text='预案日期', max_length=10),
            preserve_default=False,
        ),
    ]
