# Generated by Django 3.2.15 on 2024-11-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaapp', '0007_auto_20241113_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbyuser',
            name='yadate',
            field=models.CharField(blank=True, help_text='预案日期', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='yadate',
            field=models.CharField(blank=True, help_text='预案日期', max_length=10, null=True),
        ),
    ]
