version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 20221qaz@WSX
      MYSQL_DATABASE: kgproj
      MYSQL_USER: user
      MYSQL_PASSWORD: 20221qaz@WSX
    tmpfs:  # 确保 /tmp 可写
      - /tmp:rw,noexec,nosuid,uid=999,gid=999
    ports:
      - "3306:3306"
    volumes:
      - /etc/mysql/my.cnf:/etc/my.cnf
      - /var/mysql/logs:/var/logs:rw
      - /var/mysql/data:/var/lib/mysql:rw
    restart: unless-stopped
    privileged: true
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true
volumes:
  mysql_data: