# Generated by Django 3.2.18 on 2025-03-18 00:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='调度方案名称', max_length=512, verbose_name='调度方案名称')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 8, 48, 3, 538164), null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 8, 48, 3, 538164), null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '调度方案',
                'db_table': 'diaodu_plan',
            },
        ),
        migrations.CreateModel(
            name='WaterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='测点名称', max_length=200, verbose_name='测点名称')),
                ('inq', models.FloatField(blank=True, default=0, help_text='入库流量', verbose_name='入库流量')),
                ('inq_sed', models.FloatField(blank=True, default=0, help_text='入库含沙', verbose_name='入库含沙')),
                ('otq', models.FloatField(blank=True, default=0, help_text='出库流量', verbose_name='出库流量')),
                ('otq_sed', models.FloatField(blank=True, default=0, help_text='出库含沙', verbose_name='出库含沙')),
                ('sw', models.FloatField(blank=True, default=0, help_text='库水位', verbose_name='库水位')),
                ('capacity', models.FloatField(blank=True, default=0, help_text='库容', verbose_name='库容')),
                ('type', models.IntegerField(choices=[(0, '水库'), (1, '站点')], default=0, verbose_name='测点类型')),
                ('flow', models.FloatField(blank=True, default=0, help_text='流量', verbose_name='流量')),
                ('dt', models.DateField(blank=True, null=True, verbose_name='监测时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 8, 48, 3, 539164), null=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 8, 48, 3, 539164), null=True, verbose_name='创建时间')),
                ('plan', models.ForeignKey(blank=True, help_text='调度方案名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.ddplan', verbose_name='调度方案名称')),
            ],
            options={
                'verbose_name_plural': '水情数据',
                'db_table': 'water_record',
                'managed': True,
            },
        ),
    ]
