# Generated by Django 3.2.18 on 2025-03-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20250318_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 848423), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ddplan',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 848423), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 849423), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 16, 2, 849423), null=True, verbose_name='更新时间'),
        ),
    ]
