# Generated by Django 3.2.15 on 2024-11-13 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_auto_20241113_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddplan',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 8, 54, 45, 314559), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ddplan',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 8, 54, 45, 314559), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 8, 54, 45, 314559), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 8, 54, 45, 314559), null=True, verbose_name='更新时间'),
        ),
    ]
