# Generated by Django 3.2.18 on 2024-12-30 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20241113_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddplan',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 15, 22, 3, 568300), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ddplan',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 15, 22, 3, 568300), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 15, 22, 3, 570300), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 15, 22, 3, 570300), null=True, verbose_name='更新时间'),
        ),
    ]
