# Generated by Django 3.2.18 on 2025-01-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_auto_20241226_1503'),
        ('apiapp', '0009_auto_20241231_0815'),
    ]

    operations = [
    ]
