# Generated by Django 3.2.18 on 2025-02-06 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_auto_20250206_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddplan',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 1, 39, 906055), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ddplan',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 1, 39, 906055), null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 1, 39, 907055), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='waterrecord',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 1, 39, 906055), null=True, verbose_name='更新时间'),
        ),
    ]
